-- GLF inventory module - constraints, indexes, triggers
-- Captured from the live database before the inventory reset.
-- Tag: pre-inventory-reset (a0bdb09). Verbatim catalog output.


-- ======================================================================
-- CONSTRAINTS (PK / FK / UNIQUE / CHECK)
-- ======================================================================

ALTER TABLE public.adjustment_lines ADD CONSTRAINT adjustment_lines_adjustment_id_fkey FOREIGN KEY (adjustment_id) REFERENCES inventory_adjustments(id) ON DELETE CASCADE;
ALTER TABLE public.adjustment_lines ADD CONSTRAINT adjustment_lines_lot_id_fkey FOREIGN KEY (lot_id) REFERENCES lots(id) ON DELETE SET NULL;
ALTER TABLE public.adjustment_lines ADD CONSTRAINT adjustment_lines_pkey PRIMARY KEY (id);
ALTER TABLE public.adjustment_lines ADD CONSTRAINT adjustment_lines_product_id_fkey FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE RESTRICT;
ALTER TABLE public.correction_order_items ADD CONSTRAINT correction_order_items_correction_order_id_fkey FOREIGN KEY (correction_order_id) REFERENCES correction_orders(id) ON DELETE CASCADE;
ALTER TABLE public.correction_order_items ADD CONSTRAINT correction_order_items_current_status_check CHECK ((current_status = ANY (ARRAY['awaiting_correction'::text, 'returned_to_vendor'::text, 'received_back'::text, 'qc_passed'::text, 'qc_failed_again'::text, 'refunded_by_vendor'::text, 'closed'::text])));
ALTER TABLE public.correction_order_items ADD CONSTRAINT correction_order_items_goods_receipt_serial_id_fkey FOREIGN KEY (goods_receipt_serial_id) REFERENCES goods_receipt_serials(id);
ALTER TABLE public.correction_order_items ADD CONSTRAINT correction_order_items_latest_qc_status_check CHECK ((latest_qc_status = ANY (ARRAY['pending'::text, 'passed'::text, 'failed'::text])));
ALTER TABLE public.correction_order_items ADD CONSTRAINT correction_order_items_pkey PRIMARY KEY (id);
ALTER TABLE public.correction_order_items ADD CONSTRAINT correction_order_items_product_id_fkey FOREIGN KEY (product_id) REFERENCES products(id);
ALTER TABLE public.correction_order_refunds ADD CONSTRAINT correction_order_refunds_correction_order_id_fkey FOREIGN KEY (correction_order_id) REFERENCES correction_orders(id) ON DELETE CASCADE;
ALTER TABLE public.correction_order_refunds ADD CONSTRAINT correction_order_refunds_correction_order_item_id_fkey FOREIGN KEY (correction_order_item_id) REFERENCES correction_order_items(id) ON DELETE CASCADE;
ALTER TABLE public.correction_order_refunds ADD CONSTRAINT correction_order_refunds_pkey PRIMARY KEY (id);
ALTER TABLE public.correction_order_refunds ADD CONSTRAINT correction_order_refunds_recorded_by_fkey FOREIGN KEY (recorded_by) REFERENCES auth.users(id);
ALTER TABLE public.correction_order_refunds ADD CONSTRAINT correction_order_refunds_refund_account_id_fkey FOREIGN KEY (refund_account_id) REFERENCES payment_accounts(id);
ALTER TABLE public.correction_order_refunds ADD CONSTRAINT correction_order_refunds_refund_method_check CHECK ((refund_method = ANY (ARRAY['cash'::text, 'bank_transfer'::text, 'cheque'::text, 'adjustment'::text])));
ALTER TABLE public.correction_orders ADD CONSTRAINT correction_orders_addressed_to_type_check CHECK ((addressed_to_type = ANY (ARRAY['vendor'::text, 'factory'::text])));
ALTER TABLE public.correction_orders ADD CONSTRAINT correction_orders_closed_by_fkey FOREIGN KEY (closed_by) REFERENCES auth.users(id);
ALTER TABLE public.correction_orders ADD CONSTRAINT correction_orders_co_number_key UNIQUE (co_number);
ALTER TABLE public.correction_orders ADD CONSTRAINT correction_orders_correction_type_check CHECK ((correction_type = ANY (ARRAY['replace'::text, 'exchange'::text, 'repair'::text, 'refund'::text])));
ALTER TABLE public.correction_orders ADD CONSTRAINT correction_orders_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id);
ALTER TABLE public.correction_orders ADD CONSTRAINT correction_orders_pkey PRIMARY KEY (id);
ALTER TABLE public.correction_orders ADD CONSTRAINT correction_orders_source_type_check CHECK ((source_type = ANY (ARRAY['goods_receipt'::text, 'return'::text, 'manual'::text])));
ALTER TABLE public.correction_orders ADD CONSTRAINT correction_orders_status_check CHECK ((status = ANY (ARRAY['draft'::text, 'sent'::text, 'in_progress'::text, 'completed'::text, 'closed'::text, 'cancelled'::text])));
ALTER TABLE public.correction_qc_cycles ADD CONSTRAINT correction_qc_cycles_correction_order_item_id_cycle_number_key UNIQUE (correction_order_item_id, cycle_number);
ALTER TABLE public.correction_qc_cycles ADD CONSTRAINT correction_qc_cycles_correction_order_item_id_fkey FOREIGN KEY (correction_order_item_id) REFERENCES correction_order_items(id) ON DELETE CASCADE;
ALTER TABLE public.correction_qc_cycles ADD CONSTRAINT correction_qc_cycles_pkey PRIMARY KEY (id);
ALTER TABLE public.correction_qc_cycles ADD CONSTRAINT correction_qc_cycles_qc_checked_by_fkey FOREIGN KEY (qc_checked_by) REFERENCES auth.users(id);
ALTER TABLE public.correction_qc_cycles ADD CONSTRAINT correction_qc_cycles_qc_status_check CHECK ((qc_status = ANY (ARRAY['passed'::text, 'failed'::text])));
ALTER TABLE public.delivery_note_lines ADD CONSTRAINT delivery_note_lines_delivery_note_id_fkey FOREIGN KEY (delivery_note_id) REFERENCES delivery_notes(id) ON DELETE CASCADE;
ALTER TABLE public.delivery_note_lines ADD CONSTRAINT delivery_note_lines_invoice_line_id_fkey FOREIGN KEY (invoice_line_id) REFERENCES invoice_lines(id) ON DELETE SET NULL;
ALTER TABLE public.delivery_note_lines ADD CONSTRAINT delivery_note_lines_pkey PRIMARY KEY (id);
ALTER TABLE public.delivery_note_lines ADD CONSTRAINT delivery_note_lines_product_id_fkey FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE SET NULL;
ALTER TABLE public.delivery_notes ADD CONSTRAINT delivery_notes_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public.delivery_notes ADD CONSTRAINT delivery_notes_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE SET NULL;
ALTER TABLE public.delivery_notes ADD CONSTRAINT delivery_notes_delivered_by_user_id_fkey FOREIGN KEY (delivered_by_user_id) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public.delivery_notes ADD CONSTRAINT delivery_notes_dest_location_id_fkey FOREIGN KEY (dest_location_id) REFERENCES warehouse_locations(id) ON DELETE SET NULL;
ALTER TABLE public.delivery_notes ADD CONSTRAINT delivery_notes_invoice_id_fkey FOREIGN KEY (invoice_id) REFERENCES invoices(id) ON DELETE SET NULL;
ALTER TABLE public.delivery_notes ADD CONSTRAINT delivery_notes_operation_type_id_fkey FOREIGN KEY (operation_type_id) REFERENCES operation_types(id) ON DELETE SET NULL;
ALTER TABLE public.delivery_notes ADD CONSTRAINT delivery_notes_pkey PRIMARY KEY (id);
ALTER TABLE public.delivery_notes ADD CONSTRAINT delivery_notes_qc_by_fkey FOREIGN KEY (qc_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public.delivery_notes ADD CONSTRAINT delivery_notes_reference_key UNIQUE (reference);
ALTER TABLE public.delivery_notes ADD CONSTRAINT delivery_notes_sales_order_id_fkey FOREIGN KEY (sales_order_id) REFERENCES sales_orders(id) ON DELETE SET NULL;
ALTER TABLE public.delivery_notes ADD CONSTRAINT delivery_notes_source_location_id_fkey FOREIGN KEY (source_location_id) REFERENCES warehouse_locations(id) ON DELETE SET NULL;
ALTER TABLE public.delivery_notes ADD CONSTRAINT delivery_notes_status_check CHECK ((status = ANY (ARRAY['draft'::text, 'confirmed'::text, 'delivered'::text])));
ALTER TABLE public.delivery_notes ADD CONSTRAINT delivery_notes_warehouse_id_fkey FOREIGN KEY (warehouse_id) REFERENCES warehouses(id) ON DELETE SET NULL;
ALTER TABLE public.factory_inventory_items ADD CONSTRAINT factory_inventory_items_pkey PRIMARY KEY (id);
ALTER TABLE public.factory_stock_movements ADD CONSTRAINT factory_stock_movements_factory_inventory_item_id_fkey FOREIGN KEY (factory_inventory_item_id) REFERENCES factory_inventory_items(id) ON DELETE CASCADE;
ALTER TABLE public.factory_stock_movements ADD CONSTRAINT factory_stock_movements_movement_type_check CHECK ((movement_type = ANY (ARRAY['inbound'::text, 'consumed'::text, 'adjustment'::text, 'damaged'::text])));
ALTER TABLE public.factory_stock_movements ADD CONSTRAINT factory_stock_movements_pkey PRIMARY KEY (id);
ALTER TABLE public.factory_stock_movements ADD CONSTRAINT factory_stock_movements_recorded_by_fkey FOREIGN KEY (recorded_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public.factory_stock_movements ADD CONSTRAINT factory_stock_movements_related_work_order_id_fkey FOREIGN KEY (related_work_order_id) REFERENCES work_orders(id) ON DELETE SET NULL;
ALTER TABLE public.factory_user_assignments ADD CONSTRAINT factory_user_assignments_assigned_by_fkey FOREIGN KEY (assigned_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public.factory_user_assignments ADD CONSTRAINT factory_user_assignments_factory_id_fkey FOREIGN KEY (factory_id) REFERENCES warehouses(id) ON DELETE RESTRICT;
ALTER TABLE public.factory_user_assignments ADD CONSTRAINT factory_user_assignments_pkey PRIMARY KEY (id);
ALTER TABLE public.factory_user_assignments ADD CONSTRAINT factory_user_assignments_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.goods_receipt_lines ADD CONSTRAINT goods_receipt_lines_goods_receipt_id_fkey FOREIGN KEY (goods_receipt_id) REFERENCES goods_receipts(id) ON DELETE CASCADE;
ALTER TABLE public.goods_receipt_lines ADD CONSTRAINT goods_receipt_lines_pkey PRIMARY KEY (id);
ALTER TABLE public.goods_receipt_lines ADD CONSTRAINT goods_receipt_lines_product_id_fkey FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE RESTRICT;
ALTER TABLE public.goods_receipt_serials ADD CONSTRAINT goods_receipt_serials_barcode_value_key UNIQUE (barcode_value);
ALTER TABLE public.goods_receipt_serials ADD CONSTRAINT goods_receipt_serials_current_warehouse_id_fkey FOREIGN KEY (current_warehouse_id) REFERENCES warehouses(id) ON DELETE SET NULL;
ALTER TABLE public.goods_receipt_serials ADD CONSTRAINT goods_receipt_serials_goods_receipt_id_fkey FOREIGN KEY (goods_receipt_id) REFERENCES goods_receipts(id) ON DELETE CASCADE;
ALTER TABLE public.goods_receipt_serials ADD CONSTRAINT goods_receipt_serials_goods_receipt_line_id_fkey FOREIGN KEY (goods_receipt_line_id) REFERENCES goods_receipt_lines(id) ON DELETE CASCADE;
ALTER TABLE public.goods_receipt_serials ADD CONSTRAINT goods_receipt_serials_pkey PRIMARY KEY (id);
ALTER TABLE public.goods_receipt_serials ADD CONSTRAINT goods_receipt_serials_product_id_fkey FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE RESTRICT;
ALTER TABLE public.goods_receipt_serials ADD CONSTRAINT goods_receipt_serials_qc_checked_by_fkey FOREIGN KEY (qc_checked_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public.goods_receipt_serials ADD CONSTRAINT goods_receipt_serials_qc_status_check CHECK ((qc_status = ANY (ARRAY['pending'::text, 'passed'::text, 'failed'::text])));
ALTER TABLE public.goods_receipt_serials ADD CONSTRAINT goods_receipt_serials_reserved_for_so_id_fkey FOREIGN KEY (reserved_for_so_id) REFERENCES sales_orders(id) ON DELETE SET NULL;
ALTER TABLE public.goods_receipt_serials ADD CONSTRAINT goods_receipt_serials_serial_number_key UNIQUE (serial_number);
ALTER TABLE public.goods_receipt_serials ADD CONSTRAINT goods_receipt_serials_stock_status_check CHECK ((stock_status = ANY (ARRAY['pending'::text, 'available'::text, 'under_correction'::text, 'reserved'::text, 'sold'::text, 'returned_to_vendor'::text, 'written_off'::text, 'rejected'::text])));
ALTER TABLE public.goods_receipts ADD CONSTRAINT goods_receipts_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public.goods_receipts ADD CONSTRAINT goods_receipts_dest_location_id_fkey FOREIGN KEY (dest_location_id) REFERENCES warehouse_locations(id) ON DELETE SET NULL;
ALTER TABLE public.goods_receipts ADD CONSTRAINT goods_receipts_discrepancy_approved_by_fkey FOREIGN KEY (discrepancy_approved_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public.goods_receipts ADD CONSTRAINT goods_receipts_discrepancy_status_check CHECK ((discrepancy_status = ANY (ARRAY['matched'::text, 'quantity_mismatch'::text, 'product_mismatch'::text, 'both_mismatch'::text])));
ALTER TABLE public.goods_receipts ADD CONSTRAINT goods_receipts_gr_number_key UNIQUE (gr_number);
ALTER TABLE public.goods_receipts ADD CONSTRAINT goods_receipts_operation_type_id_fkey FOREIGN KEY (operation_type_id) REFERENCES operation_types(id) ON DELETE SET NULL;
ALTER TABLE public.goods_receipts ADD CONSTRAINT goods_receipts_pkey PRIMARY KEY (id);
ALTER TABLE public.goods_receipts ADD CONSTRAINT goods_receipts_received_by_fkey FOREIGN KEY (received_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public.goods_receipts ADD CONSTRAINT goods_receipts_source_location_id_fkey FOREIGN KEY (source_location_id) REFERENCES warehouse_locations(id) ON DELETE SET NULL;
ALTER TABLE public.goods_receipts ADD CONSTRAINT goods_receipts_source_type_check CHECK ((source_type = ANY (ARRAY['vendor_order'::text, 'work_order'::text, 'manual'::text, 'return'::text])));
ALTER TABLE public.goods_receipts ADD CONSTRAINT goods_receipts_status_check CHECK ((status = ANY (ARRAY['draft'::text, 'quantity_pending'::text, 'labels_pending'::text, 'qc_pending'::text, 'completed'::text, 'cancelled'::text])));
ALTER TABLE public.goods_receipts ADD CONSTRAINT goods_receipts_warehouse_id_fkey FOREIGN KEY (warehouse_id) REFERENCES warehouses(id) ON DELETE SET NULL;
ALTER TABLE public.internal_movement_items ADD CONSTRAINT internal_movement_items_goods_receipt_serial_id_fkey FOREIGN KEY (goods_receipt_serial_id) REFERENCES goods_receipt_serials(id) ON DELETE RESTRICT;
ALTER TABLE public.internal_movement_items ADD CONSTRAINT internal_movement_items_internal_movement_id_fkey FOREIGN KEY (internal_movement_id) REFERENCES internal_movements(id) ON DELETE CASCADE;
ALTER TABLE public.internal_movement_items ADD CONSTRAINT internal_movement_items_pkey PRIMARY KEY (id);
ALTER TABLE public.internal_movement_items ADD CONSTRAINT internal_movement_items_product_id_fkey FOREIGN KEY (product_id) REFERENCES products(id);
ALTER TABLE public.internal_movements ADD CONSTRAINT internal_movements_completed_by_fkey FOREIGN KEY (completed_by) REFERENCES auth.users(id);
ALTER TABLE public.internal_movements ADD CONSTRAINT internal_movements_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id);
ALTER TABLE public.internal_movements ADD CONSTRAINT internal_movements_from_location_type_check CHECK ((from_location_type = ANY (ARRAY['warehouse'::text, 'store_display'::text, 'under_correction'::text, 'packaging'::text])));
ALTER TABLE public.internal_movements ADD CONSTRAINT internal_movements_movement_number_key UNIQUE (movement_number);
ALTER TABLE public.internal_movements ADD CONSTRAINT internal_movements_movement_type_check CHECK ((movement_type = ANY (ARRAY['rearrangement'::text, 'display_sold'::text, 'damage_quarantine'::text, 'return_to_vendor'::text, 'cycle_count_reconciliation'::text, 'location_change'::text, 'pick_to_transit'::text])));
ALTER TABLE public.internal_movements ADD CONSTRAINT internal_movements_operation_type_id_fkey FOREIGN KEY (operation_type_id) REFERENCES operation_types(id) ON DELETE SET NULL;
ALTER TABLE public.internal_movements ADD CONSTRAINT internal_movements_pkey PRIMARY KEY (id);
ALTER TABLE public.internal_movements ADD CONSTRAINT internal_movements_status_check CHECK ((status = ANY (ARRAY['draft'::text, 'in_progress'::text, 'completed'::text, 'cancelled'::text])));
ALTER TABLE public.internal_movements ADD CONSTRAINT internal_movements_to_location_type_check CHECK ((to_location_type = ANY (ARRAY['warehouse'::text, 'store_display'::text, 'under_correction'::text, 'packaging'::text, 'vendor'::text, 'scrap'::text])));
ALTER TABLE public.internal_transfer_order_lines ADD CONSTRAINT internal_transfer_order_lines_internal_transfer_order_id_fkey FOREIGN KEY (internal_transfer_order_id) REFERENCES internal_transfer_orders(id) ON DELETE CASCADE;
ALTER TABLE public.internal_transfer_order_lines ADD CONSTRAINT internal_transfer_order_lines_line_status_check CHECK ((line_status = ANY (ARRAY['pending'::text, 'scanning'::text, 'completed'::text, 'blocked'::text])));
ALTER TABLE public.internal_transfer_order_lines ADD CONSTRAINT internal_transfer_order_lines_pkey PRIMARY KEY (id);
ALTER TABLE public.internal_transfer_order_lines ADD CONSTRAINT internal_transfer_order_lines_product_id_fkey FOREIGN KEY (product_id) REFERENCES products(id);
ALTER TABLE public.internal_transfer_order_lines ADD CONSTRAINT internal_transfer_order_lines_product_source_check CHECK ((product_source = ANY (ARRAY['display'::text, 'warehouse'::text, 'vendor'::text, 'factory'::text])));
ALTER TABLE public.internal_transfer_order_lines ADD CONSTRAINT internal_transfer_order_lines_sales_order_line_id_fkey FOREIGN KEY (sales_order_line_id) REFERENCES order_lines(id) ON DELETE CASCADE;
ALTER TABLE public.internal_transfer_orders ADD CONSTRAINT internal_transfer_orders_confirmed_by_fkey FOREIGN KEY (confirmed_by) REFERENCES auth.users(id);
ALTER TABLE public.internal_transfer_orders ADD CONSTRAINT internal_transfer_orders_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id);
ALTER TABLE public.internal_transfer_orders ADD CONSTRAINT internal_transfer_orders_dest_location_id_fkey FOREIGN KEY (dest_location_id) REFERENCES warehouse_locations(id) ON DELETE SET NULL;
ALTER TABLE public.internal_transfer_orders ADD CONSTRAINT internal_transfer_orders_ito_number_key UNIQUE (ito_number);
ALTER TABLE public.internal_transfer_orders ADD CONSTRAINT internal_transfer_orders_operation_type_id_fkey FOREIGN KEY (operation_type_id) REFERENCES operation_types(id) ON DELETE SET NULL;
ALTER TABLE public.internal_transfer_orders ADD CONSTRAINT internal_transfer_orders_pkey PRIMARY KEY (id);
ALTER TABLE public.internal_transfer_orders ADD CONSTRAINT internal_transfer_orders_sales_order_id_fkey FOREIGN KEY (sales_order_id) REFERENCES sales_orders(id) ON DELETE CASCADE;
ALTER TABLE public.internal_transfer_orders ADD CONSTRAINT internal_transfer_orders_source_location_id_fkey FOREIGN KEY (source_location_id) REFERENCES warehouse_locations(id) ON DELETE SET NULL;
ALTER TABLE public.internal_transfer_orders ADD CONSTRAINT internal_transfer_orders_status_check CHECK ((status = ANY (ARRAY['draft'::text, 'confirmed'::text, 'partial'::text, 'completed'::text, 'cancelled'::text])));
ALTER TABLE public.inventory_adjustments ADD CONSTRAINT inventory_adjustments_location_id_fkey FOREIGN KEY (location_id) REFERENCES warehouse_locations(id) ON DELETE SET NULL;
ALTER TABLE public.inventory_adjustments ADD CONSTRAINT inventory_adjustments_pkey PRIMARY KEY (id);
ALTER TABLE public.inventory_adjustments ADD CONSTRAINT inventory_adjustments_reason_check CHECK ((reason = ANY (ARRAY['count'::text, 'damage'::text, 'theft'::text, 'expiry'::text, 'correction'::text, 'other'::text])));
ALTER TABLE public.inventory_adjustments ADD CONSTRAINT inventory_adjustments_status_check CHECK ((status = ANY (ARRAY['draft'::text, 'pending_approval'::text, 'approved'::text, 'rejected'::text, 'done'::text])));
ALTER TABLE public.label_prints ADD CONSTRAINT label_prints_label_format_check CHECK ((label_format = ANY (ARRAY['standard'::text, 'thermal'::text])));
ALTER TABLE public.label_prints ADD CONSTRAINT label_prints_pkey PRIMARY KEY (id);
ALTER TABLE public.label_prints ADD CONSTRAINT label_prints_printed_by_fkey FOREIGN KEY (printed_by) REFERENCES auth.users(id);
ALTER TABLE public.label_prints ADD CONSTRAINT label_prints_product_id_fkey FOREIGN KEY (product_id) REFERENCES products(id);
ALTER TABLE public.lots ADD CONSTRAINT lots_pkey PRIMARY KEY (id);
ALTER TABLE public.lots ADD CONSTRAINT lots_product_id_fkey FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE RESTRICT;
ALTER TABLE public.lots ADD CONSTRAINT lots_product_id_name_key UNIQUE (product_id, name);
ALTER TABLE public.numbering_sequences ADD CONSTRAINT numbering_sequences_document_type_fy_label_key UNIQUE (document_type, fy_label);
ALTER TABLE public.numbering_sequences ADD CONSTRAINT numbering_sequences_pkey PRIMARY KEY (id);
ALTER TABLE public.numbering_settings ADD CONSTRAINT numbering_settings_pkey PRIMARY KEY (id);
ALTER TABLE public.numbering_settings ADD CONSTRAINT numbering_settings_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public.operation_types ADD CONSTRAINT operation_types_create_backorder_check CHECK ((create_backorder = ANY (ARRAY['ask'::text, 'always'::text, 'never'::text])));
ALTER TABLE public.operation_types ADD CONSTRAINT operation_types_default_dest_location_id_fkey FOREIGN KEY (default_dest_location_id) REFERENCES warehouse_locations(id);
ALTER TABLE public.operation_types ADD CONSTRAINT operation_types_default_source_location_id_fkey FOREIGN KEY (default_source_location_id) REFERENCES warehouse_locations(id);
ALTER TABLE public.operation_types ADD CONSTRAINT operation_types_operation_kind_check CHECK ((operation_kind = ANY (ARRAY['receipt'::text, 'delivery'::text, 'internal_transfer'::text, 'manufacturing'::text])));
ALTER TABLE public.operation_types ADD CONSTRAINT operation_types_owns_sequence_requires_fields CHECK (((NOT owns_sequence) OR ((sequence_prefix IS NOT NULL) AND (sequence_fy_label IS NOT NULL))));
ALTER TABLE public.operation_types ADD CONSTRAINT operation_types_pkey PRIMARY KEY (id);
ALTER TABLE public.operation_types ADD CONSTRAINT operation_types_returns_operation_type_id_fkey FOREIGN KEY (returns_operation_type_id) REFERENCES operation_types(id) ON DELETE SET NULL;
ALTER TABLE public.product_attribute_assignments ADD CONSTRAINT product_attribute_assignments_attribute_id_fkey FOREIGN KEY (attribute_id) REFERENCES product_attributes(id) ON DELETE CASCADE;
ALTER TABLE public.product_attribute_assignments ADD CONSTRAINT product_attribute_assignments_pkey PRIMARY KEY (id);
ALTER TABLE public.product_attribute_assignments ADD CONSTRAINT product_attribute_assignments_product_id_attribute_id_key UNIQUE (product_id, attribute_id);
ALTER TABLE public.product_attribute_assignments ADD CONSTRAINT product_attribute_assignments_product_id_fkey FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE;
ALTER TABLE public.product_attribute_values ADD CONSTRAINT product_attribute_values_attribute_id_fkey FOREIGN KEY (attribute_id) REFERENCES product_attributes(id) ON DELETE CASCADE;
ALTER TABLE public.product_attribute_values ADD CONSTRAINT product_attribute_values_pkey PRIMARY KEY (id);
ALTER TABLE public.product_attributes ADD CONSTRAINT product_attributes_display_type_check CHECK ((display_type = ANY (ARRAY['radio'::text, 'select'::text, 'color'::text, 'pills'::text])));
ALTER TABLE public.product_attributes ADD CONSTRAINT product_attributes_name_key UNIQUE (name);
ALTER TABLE public.product_attributes ADD CONSTRAINT product_attributes_pkey PRIMARY KEY (id);
ALTER TABLE public.product_categories ADD CONSTRAINT product_categories_parent_category_id_fkey FOREIGN KEY (parent_category_id) REFERENCES product_categories(id) ON DELETE SET NULL;
ALTER TABLE public.product_categories ADD CONSTRAINT product_categories_pkey PRIMARY KEY (id);
ALTER TABLE public.product_customization_options ADD CONSTRAINT product_customization_options_option_type_check CHECK ((option_type = ANY (ARRAY['size'::text, 'colour'::text, 'fabric'::text, 'polish'::text])));
ALTER TABLE public.product_customization_options ADD CONSTRAINT product_customization_options_pkey PRIMARY KEY (id);
ALTER TABLE public.product_customization_options ADD CONSTRAINT product_customization_options_product_id_fkey FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE;
ALTER TABLE public.products ADD CONSTRAINT products_category_id_fkey FOREIGN KEY (category_id) REFERENCES product_categories(id) ON DELETE SET NULL;
ALTER TABLE public.products ADD CONSTRAINT products_cost_method_check CHECK ((cost_method = ANY (ARRAY['fifo'::text, 'average'::text, 'lifo'::text])));
ALTER TABLE public.products ADD CONSTRAINT products_default_location_fk FOREIGN KEY (default_location_id) REFERENCES warehouse_locations(id) ON DELETE SET NULL;
ALTER TABLE public.products ADD CONSTRAINT products_pkey PRIMARY KEY (id);
ALTER TABLE public.products ADD CONSTRAINT products_sku_key UNIQUE (sku);
ALTER TABLE public.products ADD CONSTRAINT products_type_check CHECK ((type = ANY (ARRAY['stockable'::text, 'consumable'::text, 'service'::text])));
ALTER TABLE public.products ADD CONSTRAINT products_uom_id_fkey FOREIGN KEY (uom_id) REFERENCES units_of_measure(id);
ALTER TABLE public.qc_inspections ADD CONSTRAINT qc_inspections_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public.qc_inspections ADD CONSTRAINT qc_inspections_document_type_check CHECK ((document_type = ANY (ARRAY['ito'::text, 'goods_receipt'::text, 'delivery_note'::text, 'return'::text, 'internal_transfer'::text])));
ALTER TABLE public.qc_inspections ADD CONSTRAINT qc_inspections_inspected_by_fkey FOREIGN KEY (inspected_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public.qc_inspections ADD CONSTRAINT qc_inspections_pkey PRIMARY KEY (id);
ALTER TABLE public.qc_inspections ADD CONSTRAINT qc_inspections_product_id_fkey FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE SET NULL;
ALTER TABLE public.qc_inspections ADD CONSTRAINT qc_inspections_qc_status_check CHECK ((qc_status = ANY (ARRAY['pending'::text, 'pass'::text, 'fail'::text])));
ALTER TABLE public.reorder_rules ADD CONSTRAINT reorder_rules_location_id_fkey FOREIGN KEY (location_id) REFERENCES warehouse_locations(id) ON DELETE SET NULL;
ALTER TABLE public.reorder_rules ADD CONSTRAINT reorder_rules_pkey PRIMARY KEY (id);
ALTER TABLE public.reorder_rules ADD CONSTRAINT reorder_rules_product_id_fkey FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE;
ALTER TABLE public.reorder_rules ADD CONSTRAINT reorder_rules_warehouse_id_fkey FOREIGN KEY (warehouse_id) REFERENCES warehouses(id) ON DELETE CASCADE;
ALTER TABLE public.scan_queue ADD CONSTRAINT scan_queue_assigned_to_fkey FOREIGN KEY (assigned_to) REFERENCES auth.users(id);
ALTER TABLE public.scan_queue ADD CONSTRAINT scan_queue_document_type_check CHECK ((document_type = ANY (ARRAY['goods_receipt'::text, 'internal_transfer'::text, 'pre_delivery_qc'::text, 'return_receipt'::text, 'stock_count'::text, 'correction_order'::text, 'write_off'::text, 'delivery_note'::text, 'internal_movement'::text])));
ALTER TABLE public.scan_queue ADD CONSTRAINT scan_queue_pkey PRIMARY KEY (id);
ALTER TABLE public.scan_queue ADD CONSTRAINT scan_queue_priority_check CHECK ((priority = ANY (ARRAY['urgent'::text, 'normal'::text, 'low'::text])));
ALTER TABLE public.scan_queue ADD CONSTRAINT scan_queue_scan_status_check CHECK ((scan_status = ANY (ARRAY['pending'::text, 'in_progress'::text, 'completed'::text])));
ALTER TABLE public.scan_records ADD CONSTRAINT scan_records_pkey PRIMARY KEY (id);
ALTER TABLE public.scan_records ADD CONSTRAINT scan_records_product_id_fkey FOREIGN KEY (product_id) REFERENCES products(id);
ALTER TABLE public.scan_records ADD CONSTRAINT scan_records_scan_queue_id_fkey FOREIGN KEY (scan_queue_id) REFERENCES scan_queue(id) ON DELETE CASCADE;
ALTER TABLE public.scan_records ADD CONSTRAINT scan_records_scan_result_check CHECK ((scan_result = ANY (ARRAY['valid'::text, 'invalid'::text, 'duplicate'::text, 'not_expected'::text])));
ALTER TABLE public.scan_records ADD CONSTRAINT scan_records_scanned_by_fkey FOREIGN KEY (scanned_by) REFERENCES auth.users(id);
ALTER TABLE public.serial_counters ADD CONSTRAINT serial_counters_pkey PRIMARY KEY (prefix);
ALTER TABLE public.serial_numbers ADD CONSTRAINT serial_numbers_location_id_fkey FOREIGN KEY (location_id) REFERENCES warehouse_locations(id) ON DELETE SET NULL;
ALTER TABLE public.serial_numbers ADD CONSTRAINT serial_numbers_lot_id_fkey FOREIGN KEY (lot_id) REFERENCES lots(id) ON DELETE SET NULL;
ALTER TABLE public.serial_numbers ADD CONSTRAINT serial_numbers_pkey PRIMARY KEY (id);
ALTER TABLE public.serial_numbers ADD CONSTRAINT serial_numbers_product_id_fkey FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE RESTRICT;
ALTER TABLE public.serial_numbers ADD CONSTRAINT serial_numbers_product_id_name_key UNIQUE (product_id, name);
ALTER TABLE public.serial_numbers ADD CONSTRAINT serial_numbers_status_check CHECK ((status = ANY (ARRAY['available'::text, 'reserved'::text, 'sold'::text, 'scrapped'::text])));
ALTER TABLE public.stock_count_items ADD CONSTRAINT stock_count_items_goods_receipt_serial_id_fkey FOREIGN KEY (goods_receipt_serial_id) REFERENCES goods_receipt_serials(id) ON DELETE CASCADE;
ALTER TABLE public.stock_count_items ADD CONSTRAINT stock_count_items_pkey PRIMARY KEY (id);
ALTER TABLE public.stock_count_items ADD CONSTRAINT stock_count_items_product_id_fkey FOREIGN KEY (product_id) REFERENCES products(id);
ALTER TABLE public.stock_count_items ADD CONSTRAINT stock_count_items_scanned_by_fkey FOREIGN KEY (scanned_by) REFERENCES auth.users(id);
ALTER TABLE public.stock_count_items ADD CONSTRAINT stock_count_items_stock_count_id_fkey FOREIGN KEY (stock_count_id) REFERENCES stock_counts(id) ON DELETE CASCADE;
ALTER TABLE public.stock_counts ADD CONSTRAINT stock_counts_completed_by_fkey FOREIGN KEY (completed_by) REFERENCES auth.users(id);
ALTER TABLE public.stock_counts ADD CONSTRAINT stock_counts_count_number_key UNIQUE (count_number);
ALTER TABLE public.stock_counts ADD CONSTRAINT stock_counts_count_period_month_check CHECK (((count_period_month >= 1) AND (count_period_month <= 12)));
ALTER TABLE public.stock_counts ADD CONSTRAINT stock_counts_pkey PRIMARY KEY (id);
ALTER TABLE public.stock_counts ADD CONSTRAINT stock_counts_reconciled_by_fkey FOREIGN KEY (reconciled_by) REFERENCES auth.users(id);
ALTER TABLE public.stock_counts ADD CONSTRAINT stock_counts_skip_approved_by_fkey FOREIGN KEY (skip_approved_by) REFERENCES auth.users(id);
ALTER TABLE public.stock_counts ADD CONSTRAINT stock_counts_started_by_fkey FOREIGN KEY (started_by) REFERENCES auth.users(id);
ALTER TABLE public.stock_counts ADD CONSTRAINT stock_counts_warehouse_id_fkey FOREIGN KEY (warehouse_id) REFERENCES warehouses(id) ON DELETE SET NULL;
ALTER TABLE public.stock_move_lines ADD CONSTRAINT stock_move_lines_destination_location_id_fkey FOREIGN KEY (destination_location_id) REFERENCES warehouse_locations(id) ON DELETE RESTRICT;
ALTER TABLE public.stock_move_lines ADD CONSTRAINT stock_move_lines_lot_id_fkey FOREIGN KEY (lot_id) REFERENCES lots(id) ON DELETE SET NULL;
ALTER TABLE public.stock_move_lines ADD CONSTRAINT stock_move_lines_pkey PRIMARY KEY (id);
ALTER TABLE public.stock_move_lines ADD CONSTRAINT stock_move_lines_product_id_fkey FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE RESTRICT;
ALTER TABLE public.stock_move_lines ADD CONSTRAINT stock_move_lines_source_location_id_fkey FOREIGN KEY (source_location_id) REFERENCES warehouse_locations(id) ON DELETE RESTRICT;
ALTER TABLE public.stock_move_lines ADD CONSTRAINT stock_move_lines_stock_move_id_fkey FOREIGN KEY (stock_move_id) REFERENCES stock_moves(id) ON DELETE CASCADE;
ALTER TABLE public.stock_moves ADD CONSTRAINT stock_moves_back_order_id_fkey FOREIGN KEY (back_order_id) REFERENCES stock_moves(id) ON DELETE SET NULL;
ALTER TABLE public.stock_moves ADD CONSTRAINT stock_moves_destination_location_id_fkey FOREIGN KEY (destination_location_id) REFERENCES warehouse_locations(id) ON DELETE RESTRICT;
ALTER TABLE public.stock_moves ADD CONSTRAINT stock_moves_operation_type_check CHECK ((operation_type = ANY (ARRAY['receipt'::text, 'delivery'::text, 'internal'::text, 'adjustment'::text, 'production'::text, 'return'::text])));
ALTER TABLE public.stock_moves ADD CONSTRAINT stock_moves_pkey PRIMARY KEY (id);
ALTER TABLE public.stock_moves ADD CONSTRAINT stock_moves_reference_document_type_check CHECK (((reference_document_type IS NULL) OR (reference_document_type = ANY (ARRAY['goods_receipt'::text, 'ito'::text, 'delivery'::text, 'correction'::text, 'write_off'::text, 'stock_count'::text, 'factory'::text, 'return'::text]))));
ALTER TABLE public.stock_moves ADD CONSTRAINT stock_moves_source_location_id_fkey FOREIGN KEY (source_location_id) REFERENCES warehouse_locations(id) ON DELETE RESTRICT;
ALTER TABLE public.stock_moves ADD CONSTRAINT stock_moves_state_check CHECK ((state = ANY (ARRAY['draft'::text, 'waiting'::text, 'confirmed'::text, 'assigned'::text, 'done'::text, 'cancelled'::text])));
ALTER TABLE public.stock_reservations ADD CONSTRAINT stock_reservations_lot_id_fkey FOREIGN KEY (lot_id) REFERENCES lots(id) ON DELETE SET NULL;
ALTER TABLE public.stock_reservations ADD CONSTRAINT stock_reservations_order_line_id_fkey FOREIGN KEY (order_line_id) REFERENCES order_lines(id) ON DELETE SET NULL;
ALTER TABLE public.stock_reservations ADD CONSTRAINT stock_reservations_pkey PRIMARY KEY (id);
ALTER TABLE public.stock_reservations ADD CONSTRAINT stock_reservations_product_id_fkey FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE RESTRICT;
ALTER TABLE public.stock_reservations ADD CONSTRAINT stock_reservations_reserved_by_fkey FOREIGN KEY (reserved_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public.stock_reservations ADD CONSTRAINT stock_reservations_sales_order_id_fkey FOREIGN KEY (sales_order_id) REFERENCES sales_orders(id) ON DELETE CASCADE;
ALTER TABLE public.stock_reservations ADD CONSTRAINT stock_reservations_serial_number_id_fkey FOREIGN KEY (serial_number_id) REFERENCES goods_receipt_serials(id) ON DELETE SET NULL;
ALTER TABLE public.stock_reservations ADD CONSTRAINT stock_reservations_status_check CHECK ((status = ANY (ARRAY['reserved'::text, 'released'::text, 'delivered'::text])));
ALTER TABLE public.transfer_lines ADD CONSTRAINT transfer_lines_pkey PRIMARY KEY (id);
ALTER TABLE public.transfer_lines ADD CONSTRAINT transfer_lines_product_id_fkey FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE RESTRICT;
ALTER TABLE public.transfer_lines ADD CONSTRAINT transfer_lines_transfer_id_fkey FOREIGN KEY (transfer_id) REFERENCES transfers(id) ON DELETE CASCADE;
ALTER TABLE public.transfers ADD CONSTRAINT transfers_back_order_of_fkey FOREIGN KEY (back_order_of) REFERENCES transfers(id) ON DELETE SET NULL;
ALTER TABLE public.transfers ADD CONSTRAINT transfers_from_warehouse_id_fkey FOREIGN KEY (from_warehouse_id) REFERENCES warehouses(id) ON DELETE SET NULL;
ALTER TABLE public.transfers ADD CONSTRAINT transfers_pkey PRIMARY KEY (id);
ALTER TABLE public.transfers ADD CONSTRAINT transfers_product_availability_check CHECK ((product_availability = ANY (ARRAY['available'::text, 'partial'::text, 'not_available'::text])));
ALTER TABLE public.transfers ADD CONSTRAINT transfers_state_check CHECK ((state = ANY (ARRAY['draft'::text, 'waiting'::text, 'ready'::text, 'done'::text, 'cancelled'::text])));
ALTER TABLE public.transfers ADD CONSTRAINT transfers_to_warehouse_id_fkey FOREIGN KEY (to_warehouse_id) REFERENCES warehouses(id) ON DELETE SET NULL;
ALTER TABLE public.units_of_measure ADD CONSTRAINT units_of_measure_name_key UNIQUE (name);
ALTER TABLE public.units_of_measure ADD CONSTRAINT units_of_measure_pkey PRIMARY KEY (id);
ALTER TABLE public.units_of_measure ADD CONSTRAINT units_of_measure_uom_type_check CHECK ((uom_type = ANY (ARRAY['unit'::text, 'reference'::text, 'bigger'::text, 'smaller'::text])));
ALTER TABLE public.warehouse_locations ADD CONSTRAINT warehouse_locations_parent_location_id_fkey FOREIGN KEY (parent_location_id) REFERENCES warehouse_locations(id) ON DELETE SET NULL;
ALTER TABLE public.warehouse_locations ADD CONSTRAINT warehouse_locations_pkey PRIMARY KEY (id);
ALTER TABLE public.warehouse_locations ADD CONSTRAINT warehouse_locations_removal_strategy_check CHECK ((removal_strategy = ANY (ARRAY['fifo'::text, 'lifo'::text, 'closest'::text, 'manual'::text])));
ALTER TABLE public.warehouse_locations ADD CONSTRAINT warehouse_locations_type_check CHECK ((type = ANY (ARRAY['internal'::text, 'customer'::text, 'vendor'::text, 'transit'::text, 'virtual'::text, 'production'::text])));
ALTER TABLE public.warehouse_locations ADD CONSTRAINT warehouse_locations_warehouse_id_code_key UNIQUE (warehouse_id, code);
ALTER TABLE public.warehouse_locations ADD CONSTRAINT warehouse_locations_warehouse_id_fkey FOREIGN KEY (warehouse_id) REFERENCES warehouses(id) ON DELETE CASCADE;
ALTER TABLE public.warehouses ADD CONSTRAINT warehouses_code_key UNIQUE (code);
ALTER TABLE public.warehouses ADD CONSTRAINT warehouses_default_delivery_fk FOREIGN KEY (default_delivery_location_id) REFERENCES warehouse_locations(id) ON DELETE SET NULL;
ALTER TABLE public.warehouses ADD CONSTRAINT warehouses_default_internal_fk FOREIGN KEY (default_internal_location_id) REFERENCES warehouse_locations(id) ON DELETE SET NULL;
ALTER TABLE public.warehouses ADD CONSTRAINT warehouses_default_receipt_fk FOREIGN KEY (default_receipt_location_id) REFERENCES warehouse_locations(id) ON DELETE SET NULL;
ALTER TABLE public.warehouses ADD CONSTRAINT warehouses_pkey PRIMARY KEY (id);
ALTER TABLE public.write_off_items ADD CONSTRAINT write_off_items_goods_receipt_serial_id_fkey FOREIGN KEY (goods_receipt_serial_id) REFERENCES goods_receipt_serials(id);
ALTER TABLE public.write_off_items ADD CONSTRAINT write_off_items_pkey PRIMARY KEY (id);
ALTER TABLE public.write_off_items ADD CONSTRAINT write_off_items_product_id_fkey FOREIGN KEY (product_id) REFERENCES products(id);
ALTER TABLE public.write_off_items ADD CONSTRAINT write_off_items_write_off_record_id_fkey FOREIGN KEY (write_off_record_id) REFERENCES write_off_records(id) ON DELETE CASCADE;
ALTER TABLE public.write_off_items ADD CONSTRAINT write_off_items_write_off_record_id_goods_receipt_serial_id_key UNIQUE (write_off_record_id, goods_receipt_serial_id);
ALTER TABLE public.write_off_records ADD CONSTRAINT write_off_reason_not_empty CHECK (((status <> 'approved'::text) OR (length(TRIM(BOTH FROM reason)) > 0)));
ALTER TABLE public.write_off_records ADD CONSTRAINT write_off_records_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES auth.users(id);
ALTER TABLE public.write_off_records ADD CONSTRAINT write_off_records_cancelled_by_fkey FOREIGN KEY (cancelled_by) REFERENCES auth.users(id);
ALTER TABLE public.write_off_records ADD CONSTRAINT write_off_records_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id);
ALTER TABLE public.write_off_records ADD CONSTRAINT write_off_records_pkey PRIMARY KEY (id);
ALTER TABLE public.write_off_records ADD CONSTRAINT write_off_records_source_type_check CHECK ((source_type = ANY (ARRAY['stock_count'::text, 'correction_order'::text, 'return'::text, 'damage_report'::text, 'manual'::text])));
ALTER TABLE public.write_off_records ADD CONSTRAINT write_off_records_status_check CHECK ((status = ANY (ARRAY['draft'::text, 'approved'::text, 'cancelled'::text])));
ALTER TABLE public.write_off_records ADD CONSTRAINT write_off_records_wf_number_key UNIQUE (wf_number);
ALTER TABLE public.write_off_records ADD CONSTRAINT write_off_records_write_off_type_check CHECK ((write_off_type = ANY (ARRAY['damage'::text, 'loss'::text, 'theft'::text, 'obsolete'::text, 'scrap'::text, 'count_missing'::text, 'qc_unsalvageable'::text, 'other'::text])));

-- ======================================================================
-- INDEXES
-- ======================================================================

CREATE UNIQUE INDEX adjustment_lines_pkey ON public.adjustment_lines USING btree (id);
CREATE UNIQUE INDEX correction_order_items_pkey ON public.correction_order_items USING btree (id);
CREATE INDEX idx_coi_co ON public.correction_order_items USING btree (correction_order_id);
CREATE INDEX idx_coi_serial ON public.correction_order_items USING btree (goods_receipt_serial_id);
CREATE UNIQUE INDEX correction_order_refunds_pkey ON public.correction_order_refunds USING btree (id);
CREATE INDEX idx_cor_co ON public.correction_order_refunds USING btree (correction_order_id);
CREATE UNIQUE INDEX correction_orders_co_number_key ON public.correction_orders USING btree (co_number);
CREATE UNIQUE INDEX correction_orders_pkey ON public.correction_orders USING btree (id);
CREATE INDEX idx_co_source ON public.correction_orders USING btree (source_type, source_document_id);
CREATE INDEX idx_co_status_created ON public.correction_orders USING btree (status, created_at DESC);
CREATE UNIQUE INDEX correction_qc_cycles_correction_order_item_id_cycle_number_key ON public.correction_qc_cycles USING btree (correction_order_item_id, cycle_number);
CREATE UNIQUE INDEX correction_qc_cycles_pkey ON public.correction_qc_cycles USING btree (id);
CREATE INDEX idx_cqc_item ON public.correction_qc_cycles USING btree (correction_order_item_id);
CREATE UNIQUE INDEX delivery_note_lines_pkey ON public.delivery_note_lines USING btree (id);
CREATE INDEX idx_dnl_dn ON public.delivery_note_lines USING btree (delivery_note_id);
CREATE INDEX idx_dnl_invoice_line ON public.delivery_note_lines USING btree (invoice_line_id);
CREATE UNIQUE INDEX delivery_notes_pkey ON public.delivery_notes USING btree (id);
CREATE UNIQUE INDEX delivery_notes_reference_key ON public.delivery_notes USING btree (reference);
CREATE INDEX idx_delivery_notes_invoice ON public.delivery_notes USING btree (invoice_id);
CREATE INDEX idx_delivery_notes_sales_order ON public.delivery_notes USING btree (sales_order_id);
CREATE INDEX idx_delivery_notes_status ON public.delivery_notes USING btree (status);
CREATE UNIQUE INDEX factory_inventory_items_pkey ON public.factory_inventory_items USING btree (id);
CREATE UNIQUE INDEX factory_stock_movements_pkey ON public.factory_stock_movements USING btree (id);
CREATE INDEX idx_fsm_item ON public.factory_stock_movements USING btree (factory_inventory_item_id);
CREATE INDEX idx_fsm_wo ON public.factory_stock_movements USING btree (related_work_order_id);
CREATE UNIQUE INDEX factory_user_assignments_pkey ON public.factory_user_assignments USING btree (id);
CREATE UNIQUE INDEX factory_user_assignments_unique_active ON public.factory_user_assignments USING btree (user_id, factory_id) WHERE is_active;
CREATE UNIQUE INDEX goods_receipt_lines_pkey ON public.goods_receipt_lines USING btree (id);
CREATE INDEX idx_grl_gr ON public.goods_receipt_lines USING btree (goods_receipt_id);
CREATE INDEX idx_grl_product ON public.goods_receipt_lines USING btree (product_id);
CREATE UNIQUE INDEX goods_receipt_serials_barcode_value_key ON public.goods_receipt_serials USING btree (barcode_value);
CREATE UNIQUE INDEX goods_receipt_serials_pkey ON public.goods_receipt_serials USING btree (id);
CREATE UNIQUE INDEX goods_receipt_serials_serial_number_key ON public.goods_receipt_serials USING btree (serial_number);
CREATE INDEX idx_grs_barcode ON public.goods_receipt_serials USING btree (barcode_value);
CREATE INDEX idx_grs_gr ON public.goods_receipt_serials USING btree (goods_receipt_id);
CREATE INDEX idx_grs_product_status ON public.goods_receipt_serials USING btree (product_id, stock_status);
CREATE INDEX idx_grs_serial ON public.goods_receipt_serials USING btree (serial_number);
CREATE UNIQUE INDEX goods_receipts_gr_number_key ON public.goods_receipts USING btree (gr_number);
CREATE UNIQUE INDEX goods_receipts_pkey ON public.goods_receipts USING btree (id);
CREATE INDEX idx_gr_source ON public.goods_receipts USING btree (source_type, source_document_id);
CREATE INDEX idx_gr_status ON public.goods_receipts USING btree (status);
CREATE INDEX idx_imi_movement ON public.internal_movement_items USING btree (internal_movement_id);
CREATE INDEX idx_imi_serial ON public.internal_movement_items USING btree (goods_receipt_serial_id);
CREATE UNIQUE INDEX internal_movement_items_pkey ON public.internal_movement_items USING btree (id);
CREATE INDEX idx_im_status_created ON public.internal_movements USING btree (status, created_at DESC);
CREATE INDEX idx_im_type_created ON public.internal_movements USING btree (movement_type, created_at DESC);
CREATE UNIQUE INDEX internal_movements_movement_number_key ON public.internal_movements USING btree (movement_number);
CREATE UNIQUE INDEX internal_movements_pkey ON public.internal_movements USING btree (id);
CREATE INDEX idx_ito_lines_ito ON public.internal_transfer_order_lines USING btree (internal_transfer_order_id);
CREATE UNIQUE INDEX internal_transfer_order_lines_pkey ON public.internal_transfer_order_lines USING btree (id);
CREATE INDEX idx_ito_sales_order ON public.internal_transfer_orders USING btree (sales_order_id);
CREATE INDEX idx_ito_status_created ON public.internal_transfer_orders USING btree (status, created_at DESC);
CREATE UNIQUE INDEX internal_transfer_orders_ito_number_key ON public.internal_transfer_orders USING btree (ito_number);
CREATE UNIQUE INDEX internal_transfer_orders_pkey ON public.internal_transfer_orders USING btree (id);
CREATE UNIQUE INDEX inventory_adjustments_pkey ON public.inventory_adjustments USING btree (id);
CREATE INDEX idx_label_prints_product ON public.label_prints USING btree (product_id, printed_at DESC);
CREATE INDEX idx_label_prints_serial ON public.label_prints USING btree (serial_number);
CREATE UNIQUE INDEX label_prints_pkey ON public.label_prints USING btree (id);
CREATE UNIQUE INDEX lots_pkey ON public.lots USING btree (id);
CREATE UNIQUE INDEX lots_product_id_name_key ON public.lots USING btree (product_id, name);
CREATE UNIQUE INDEX numbering_sequences_document_type_fy_label_key ON public.numbering_sequences USING btree (document_type, fy_label);
CREATE UNIQUE INDEX numbering_sequences_pkey ON public.numbering_sequences USING btree (id);
CREATE UNIQUE INDEX numbering_settings_pkey ON public.numbering_settings USING btree (id);
CREATE UNIQUE INDEX operation_types_pkey ON public.operation_types USING btree (id);
CREATE UNIQUE INDEX product_attribute_assignments_pkey ON public.product_attribute_assignments USING btree (id);
CREATE UNIQUE INDEX product_attribute_assignments_product_id_attribute_id_key ON public.product_attribute_assignments USING btree (product_id, attribute_id);
CREATE UNIQUE INDEX product_attribute_values_pkey ON public.product_attribute_values USING btree (id);
CREATE UNIQUE INDEX product_attributes_name_key ON public.product_attributes USING btree (name);
CREATE UNIQUE INDEX product_attributes_pkey ON public.product_attributes USING btree (id);
CREATE UNIQUE INDEX product_categories_pkey ON public.product_categories USING btree (id);
CREATE UNIQUE INDEX product_customization_options_pkey ON public.product_customization_options USING btree (id);
CREATE UNIQUE INDEX product_customization_options_uniq ON public.product_customization_options USING btree (product_id, option_type, option_value);
CREATE UNIQUE INDEX products_barcode_unique ON public.products USING btree (barcode) WHERE (barcode IS NOT NULL);
CREATE UNIQUE INDEX products_pkey ON public.products USING btree (id);
CREATE UNIQUE INDEX products_sku_key ON public.products USING btree (sku);
CREATE INDEX idx_qc_inspections_document ON public.qc_inspections USING btree (document_type, document_id);
CREATE INDEX idx_qc_inspections_serial ON public.qc_inspections USING btree (serial_number);
CREATE UNIQUE INDEX qc_inspections_pkey ON public.qc_inspections USING btree (id);
CREATE UNIQUE INDEX uq_qc_inspections_doc_serial ON public.qc_inspections USING btree (document_type, document_id, serial_number) WHERE (serial_number IS NOT NULL);
CREATE UNIQUE INDEX reorder_rules_pkey ON public.reorder_rules USING btree (id);
CREATE INDEX idx_scan_queue_status_created ON public.scan_queue USING btree (scan_status, created_at DESC);
CREATE UNIQUE INDEX scan_queue_pkey ON public.scan_queue USING btree (id);
CREATE INDEX idx_scan_records_barcode ON public.scan_records USING btree (barcode);
CREATE INDEX idx_scan_records_queue_time ON public.scan_records USING btree (scan_queue_id, scanned_at DESC);
CREATE INDEX idx_scan_records_serial ON public.scan_records USING btree (serial_number);
CREATE UNIQUE INDEX scan_records_pkey ON public.scan_records USING btree (id);
CREATE UNIQUE INDEX serial_counters_pkey ON public.serial_counters USING btree (prefix);
CREATE UNIQUE INDEX serial_numbers_pkey ON public.serial_numbers USING btree (id);
CREATE UNIQUE INDEX serial_numbers_product_id_name_key ON public.serial_numbers USING btree (product_id, name);
CREATE INDEX idx_sci_count_status ON public.stock_count_items USING btree (stock_count_id, count_status);
CREATE INDEX idx_sci_serial ON public.stock_count_items USING btree (goods_receipt_serial_id);
CREATE UNIQUE INDEX stock_count_items_pkey ON public.stock_count_items USING btree (id);
CREATE UNIQUE INDEX uq_sci_count_serial ON public.stock_count_items USING btree (stock_count_id, goods_receipt_serial_id);
CREATE UNIQUE INDEX stock_counts_count_number_key ON public.stock_counts USING btree (count_number);
CREATE UNIQUE INDEX stock_counts_pkey ON public.stock_counts USING btree (id);
CREATE UNIQUE INDEX uq_stock_counts_period_wh ON public.stock_counts USING btree (count_period_year, count_period_month, COALESCE(warehouse_id, '00000000-0000-0000-0000-000000000000'::uuid));
CREATE INDEX stock_move_lines_move_idx ON public.stock_move_lines USING btree (stock_move_id);
CREATE UNIQUE INDEX stock_move_lines_pkey ON public.stock_move_lines USING btree (id);
CREATE INDEX stock_move_lines_product_idx ON public.stock_move_lines USING btree (product_id);
CREATE INDEX stock_moves_operation_idx ON public.stock_moves USING btree (operation_type);
CREATE UNIQUE INDEX stock_moves_pkey ON public.stock_moves USING btree (id);
CREATE INDEX stock_moves_state_idx ON public.stock_moves USING btree (state);
CREATE INDEX idx_stock_reservations_product ON public.stock_reservations USING btree (product_id);
CREATE INDEX idx_stock_reservations_sales_order ON public.stock_reservations USING btree (sales_order_id);
CREATE INDEX idx_stock_reservations_serial ON public.stock_reservations USING btree (serial_number_id);
CREATE INDEX idx_stock_reservations_status ON public.stock_reservations USING btree (status);
CREATE UNIQUE INDEX stock_reservations_pkey ON public.stock_reservations USING btree (id);
CREATE UNIQUE INDEX uq_stock_reservations_active_serial ON public.stock_reservations USING btree (serial_number_id) WHERE ((status = 'reserved'::text) AND (serial_number_id IS NOT NULL));
CREATE UNIQUE INDEX transfer_lines_pkey ON public.transfer_lines USING btree (id);
CREATE INDEX transfer_lines_transfer_idx ON public.transfer_lines USING btree (transfer_id);
CREATE UNIQUE INDEX transfers_pkey ON public.transfers USING btree (id);
CREATE UNIQUE INDEX units_of_measure_name_key ON public.units_of_measure USING btree (name);
CREATE UNIQUE INDEX units_of_measure_pkey ON public.units_of_measure USING btree (id);
CREATE UNIQUE INDEX warehouse_locations_pkey ON public.warehouse_locations USING btree (id);
CREATE UNIQUE INDEX warehouse_locations_warehouse_id_code_key ON public.warehouse_locations USING btree (warehouse_id, code);
CREATE UNIQUE INDEX warehouses_code_key ON public.warehouses USING btree (code);
CREATE UNIQUE INDEX warehouses_pkey ON public.warehouses USING btree (id);
CREATE INDEX idx_wfi_record ON public.write_off_items USING btree (write_off_record_id);
CREATE INDEX idx_wfi_serial ON public.write_off_items USING btree (goods_receipt_serial_id);
CREATE UNIQUE INDEX write_off_items_pkey ON public.write_off_items USING btree (id);
CREATE UNIQUE INDEX write_off_items_write_off_record_id_goods_receipt_serial_id_key ON public.write_off_items USING btree (write_off_record_id, goods_receipt_serial_id);
CREATE INDEX idx_wf_status_created ON public.write_off_records USING btree (status, created_at DESC);
CREATE INDEX idx_wf_type ON public.write_off_records USING btree (write_off_type);
CREATE UNIQUE INDEX write_off_records_pkey ON public.write_off_records USING btree (id);
CREATE UNIQUE INDEX write_off_records_wf_number_key ON public.write_off_records USING btree (wf_number);

-- ======================================================================
-- TRIGGERS
-- ======================================================================

CREATE TRIGGER adjustment_lines_set_updated_at BEFORE UPDATE ON public.adjustment_lines FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_coi_updated BEFORE UPDATE ON public.correction_order_items FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_co_updated BEFORE UPDATE ON public.correction_orders FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_dnl_updated_at BEFORE UPDATE ON public.delivery_note_lines FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER delivery_notes_set_reference_trg BEFORE INSERT ON public.delivery_notes FOR EACH ROW EXECUTE FUNCTION delivery_notes_set_reference();
CREATE TRIGGER trg_notify_delivery_note AFTER INSERT ON public.delivery_notes FOR EACH ROW EXECUTE FUNCTION tg_notify_delivery_note();
CREATE TRIGGER update_delivery_notes_updated_at BEFORE UPDATE ON public.delivery_notes FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_fii_updated_at BEFORE UPDATE ON public.factory_inventory_items FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_grl_updated_at BEFORE UPDATE ON public.goods_receipt_lines FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_enforce_grs_reservation_status BEFORE INSERT OR UPDATE ON public.goods_receipt_serials FOR EACH ROW EXECUTE FUNCTION enforce_grs_reservation_status();
CREATE TRIGGER trg_gr_serial_auto_co AFTER UPDATE OF stock_status ON public.goods_receipt_serials FOR EACH ROW EXECUTE FUNCTION trg_gr_serial_after_under_correction();
CREATE TRIGGER trg_grs_updated_at BEFORE UPDATE ON public.goods_receipt_serials FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_enforce_gr_discrepancy_approval BEFORE UPDATE ON public.goods_receipts FOR EACH ROW EXECUTE FUNCTION enforce_gr_discrepancy_approval();
CREATE TRIGGER trg_gr_fill_default_locations BEFORE INSERT ON public.goods_receipts FOR EACH ROW EXECUTE FUNCTION gr_fill_default_locations();
CREATE TRIGGER trg_gr_set_number BEFORE INSERT ON public.goods_receipts FOR EACH ROW EXECUTE FUNCTION gr_set_number();
CREATE TRIGGER trg_gr_updated_at BEFORE UPDATE ON public.goods_receipts FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_notify_goods_receipt AFTER INSERT OR UPDATE ON public.goods_receipts FOR EACH ROW EXECUTE FUNCTION tg_notify_goods_receipt();
CREATE TRIGGER trg_imi_updated_at BEFORE UPDATE ON public.internal_movement_items FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_im_set_number BEFORE INSERT ON public.internal_movements FOR EACH ROW EXECUTE FUNCTION im_set_number();
CREATE TRIGGER trg_im_updated_at BEFORE UPDATE ON public.internal_movements FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_ito_after_line_update AFTER UPDATE OF quantity_scanned, line_status ON public.internal_transfer_order_lines FOR EACH ROW EXECUTE FUNCTION ito_after_line_update();
CREATE TRIGGER trg_ito_line_before_update BEFORE UPDATE OF quantity_scanned ON public.internal_transfer_order_lines FOR EACH ROW EXECUTE FUNCTION ito_line_cascade_status();
CREATE TRIGGER trg_ito_lines_updated_at BEFORE UPDATE ON public.internal_transfer_order_lines FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_ito_updated_at BEFORE UPDATE ON public.internal_transfer_orders FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER inventory_adjustments_set_updated_at BEFORE UPDATE ON public.inventory_adjustments FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER lots_set_updated_at BEFORE UPDATE ON public.lots FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_numbering_settings_updated_at BEFORE UPDATE ON public.numbering_settings FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_ot_updated BEFORE UPDATE ON public.operation_types FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_pc_updated BEFORE UPDATE ON public.product_categories FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_pco_updated_at BEFORE UPDATE ON public.product_customization_options FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER products_set_updated_at BEFORE UPDATE ON public.products FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_qc_inspections_updated_at BEFORE UPDATE ON public.qc_inspections FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER reorder_rules_set_updated_at BEFORE UPDATE ON public.reorder_rules FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_scan_queue_updated_at BEFORE UPDATE ON public.scan_queue FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_scan_record_to_ito_line AFTER INSERT ON public.scan_records FOR EACH ROW EXECUTE FUNCTION scan_record_update_ito_line();
CREATE TRIGGER serial_numbers_set_updated_at BEFORE UPDATE ON public.serial_numbers FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_stock_count_items_updated BEFORE UPDATE ON public.stock_count_items FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_stock_counts_number BEFORE INSERT ON public.stock_counts FOR EACH ROW EXECUTE FUNCTION stock_counts_set_number();
CREATE TRIGGER trg_stock_counts_updated BEFORE UPDATE ON public.stock_counts FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER stock_move_lines_set_updated_at BEFORE UPDATE ON public.stock_move_lines FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_prevent_stock_move_line_mutation BEFORE DELETE OR UPDATE ON public.stock_move_lines FOR EACH ROW EXECUTE FUNCTION prevent_stock_move_line_mutation();
CREATE TRIGGER stock_moves_set_updated_at BEFORE UPDATE ON public.stock_moves FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_prevent_stock_move_mutation BEFORE DELETE OR UPDATE ON public.stock_moves FOR EACH ROW EXECUTE FUNCTION prevent_stock_move_mutation();
CREATE TRIGGER stock_reservations_updated_at BEFORE UPDATE ON public.stock_reservations FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER transfer_lines_set_updated_at BEFORE UPDATE ON public.transfer_lines FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER transfers_set_updated_at BEFORE UPDATE ON public.transfers FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_uom_updated BEFORE UPDATE ON public.units_of_measure FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER warehouse_locations_set_updated_at BEFORE UPDATE ON public.warehouse_locations FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER warehouses_set_updated_at BEFORE UPDATE ON public.warehouses FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_wf_set_number BEFORE INSERT ON public.write_off_records FOR EACH ROW EXECUTE FUNCTION wf_set_number();
CREATE TRIGGER trg_wf_updated_at BEFORE UPDATE ON public.write_off_records FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
