import type { Quotation } from '@/lib/data/sales/types';
import { getTaxRules } from '@/lib/data/sales/storage';

export function downloadQuotationPdf(quotation: Quotation) {
  const taxRules = getTaxRules();
  const linesHtml = quotation.lines.map((line, i) =>
    `<tr><td style="padding:8px;border-bottom:1px solid #e5e7eb">${i+1}</td><td style="padding:8px;border-bottom:1px solid #e5e7eb">${line.productName}</td><td style="padding:8px;border-bottom:1px solid #e5e7eb;text-align:right">${line.quantity}</td><td style="padding:8px;border-bottom:1px solid #e5e7eb;text-align:right">₹${line.unitPrice.toLocaleString('en-IN')}</td><td style="padding:8px;border-bottom:1px solid #e5e7eb;text-align:right;font-weight:600">₹${line.total.toLocaleString('en-IN')}</td></tr>`
  ).join('');
  const html = `<!DOCTYPE html><html><head><meta charset="utf-8"><title>${quotation.reference}</title><style>body{font-family:Arial,sans-serif;color:#1a1a1a;margin:0;padding:40px}h1{font-size:28px;margin:0 0 4px}table{width:100%;border-collapse:collapse;margin-bottom:24px}th{text-align:left;padding:10px 8px;background:#f3f4f6;font-size:12px;text-transform:uppercase;border-bottom:2px solid #d1d5db}.totals{width:280px;margin-left:auto;font-size:14px}.totals tr td{padding:6px 8px}.totals .grand{font-size:18px;font-weight:700;border-top:2px solid #1a1a1a}@media print{body{padding:20px}}</style></head><body><h1>${quotation.reference}</h1><p style="color:#6b7280;margin:0 0 24px">Quotation</p><div style="display:flex;justify-content:space-between;margin-bottom:32px"><div style="font-size:13px"><strong>Customer</strong><br>${quotation.customerName}</div><div style="text-align:right;font-size:13px"><strong>Details</strong><br>Date: ${quotation.quotationDate}<br>Valid Until: ${quotation.validUntil}<br>Payment: ${quotation.paymentTerms||'—'}</div></div><table><thead><tr><th>#</th><th>Product</th><th style="text-align:right">Qty</th><th style="text-align:right">Unit Price</th><th style="text-align:right">Total</th></tr></thead><tbody>${linesHtml}</tbody></table><table class="totals"><tr><td>Subtotal</td><td style="text-align:right">₹${quotation.subtotal.toLocaleString('en-IN')}</td></tr>${quotation.discountAmount>0?`<tr><td>Discount</td><td style="text-align:right;color:#16a34a">-₹${quotation.discountAmount.toLocaleString('en-IN')}</td></tr>`:''}<tr><td>Tax</td><td style="text-align:right">₹${quotation.taxAmount.toLocaleString('en-IN')}</td></tr><tr class="grand"><td>Total</td><td style="text-align:right">₹${quotation.total.toLocaleString('en-IN')}</td></tr></table>${quotation.notes?`<div style="margin-top:32px;font-size:12px;color:#6b7280"><strong>Notes</strong><br>${quotation.notes}</div>`:''}</body></html>`;
  const win = window.open('', '_blank');
  if (win) { win.document.write(html); win.document.close(); setTimeout(() => win.print(), 300); }
}