// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mdtwvuiakvxoqvksemyt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1kdHd2dWlha3Z4b3F2a3NlbXl0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzY4MzI5NTksImV4cCI6MjA5MjQwODk1OX0.nvGe32DozgOUfEQlAjAG5Hplm-8ypkTRWn5fZqetqm0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});