// Shared navigation items for the HR/Employees module
export const HR_NAV = [
  { label: 'Overview', href: '/employees' },
  { label: 'Directory', href: '/employees/directory' },
  { label: 'Departments', href: '/employees/departments' },
  { label: 'Contracts', href: '/employees/contracts' },
  { label: 'Clock In/Out', href: '/attendance/clock-in' },
  { label: 'My Attendance', href: '/attendance/my' },
  { label: 'Team Attendance', href: '/attendance/team' },
  { label: 'Admin', href: '/attendance/admin' },
  { label: 'Locations', href: '/attendance/locations' },
  { label: 'Holidays', href: '/attendance/holidays' },
  { label: 'Work Schedules', href: '/attendance/work-schedules' },
  { label: 'Roster Planning', href: '/attendance/roster' },
  { label: 'Roster Reschedule', href: '/attendance/roster/reschedule' },
  { label: 'My Leaves', href: '/leave/my-leaves' },
  { label: 'Apply Leave', href: '/leave/apply' },
  { label: 'Team Leaves', href: '/leave/team' },
  { label: 'Leave Calendar', href: '/leave/calendar' },
  { label: 'Leave Requests (Admin)', href: '/leave/admin/requests' },
  { label: 'Leave Balances (Admin)', href: '/leave/admin/balances' },
  { label: 'Leave Entitlements (Admin)', href: '/leave/admin/entitlements' },
  { label: 'Leave Types (Admin)', href: '/leave/admin/types' },
  { label: 'Comp Off (Admin)', href: '/leave/admin/comp-off' },
];
