// Settings Module Navigation - shared across all settings pages
export const SETTINGS_NAV = [
  { label: 'General', href: '/settings' },
  { label: 'Company', href: '/settings/company' },
  { label: 'Users', href: '/settings/users' },
  { label: 'Roles', href: '/settings/roles' },
  { label: 'Vendors', href: '/settings/vendors' },
  { label: 'Work Schedules', href: '/settings/work-schedules' },
  { label: 'Holidays', href: '/settings/holidays' },
  { label: 'Payroll', href: '/settings/payroll' },
  { label: 'Notifications', href: '/settings/notifications' },
  { label: 'Customization', href: '/settings/customization' },
  { label: 'CRM Pipelines', href: '/settings/crm-pipelines' },
  { label: 'Data Schema', href: '/settings/data-schema' },
  { label: 'Accessibility', href: '/settings/accessibility' },
  { label: 'Price Approvals', href: '/settings/price-approvals' },
  { label: 'Numbering', href: '/settings/numbering' },
  { label: 'Payment Accounts', href: '/settings/payment-accounts' },
  { label: 'Audit Logs', href: '/audit-logs' },
  { label: 'Backups', href: '/settings/backups' },
];
